name: build test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    #- name: Install npm dependencies
     # run: npm install
    #- name: Run build task
     # run: npm run build --if-present
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: 'utf8'
        mysql database: 'pizzaorder'
        mysql user: 'pizza'
        mysql password: 'toor'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build

      #- name: Deploy to Server
      #uses: easingthemes/ssh-deploy@v2.1.5
      #env:
        #SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        #ARGS: "--delete"
        #SOURCE: "build/libs"
        #REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        #REMOTE_USER: ${{ secrets.REMOTE_USER }}
        #REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        #TARGET: ${{ secrets.REMOTE_TARGET }}
        #EXCLUDE: "/dist/, /node_modules/"
