- name: ssh deploy
  # You may pin to the exact commit or the version.
  # uses: easingthemes/ssh-deploy@9ab39935552e9fe6706e9c9bf2a70a3328a4a5e6
  uses: easingthemes/ssh-deploy@9ab39935552e9fe6706e9c9bf2a70a3328a4a5e6
  with:
    # Private Key
    SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
    # Remote host
    REMOTE_HOST: lmu.makerdark98.dev
    # Remote user
    REMOTE_USER: sogong
    # Remote port
    REMOTE_PORT: 7722 # optional, default is 22
    # Source directory
    SOURCE: /home/sogong/software
    # Target directory
    TARGET: # optional, default is /home/REMOTE_USER/
    # Arguments to pass to rsync
    ARGS: # optional, default is -rltgoDzvO
    # An array of folder to exclude
    EXCLUDE: # optional, default is 
